In [1]:
import numpy as np

In [4]:
inputArray = np.array ([
    [1, 2, 3],
    [4, 5, 6]
])

In [5]:
inputArray

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
inputArray.shape

(2, 3)

In [8]:
inputArray[0][1]

2

In [9]:
inputArray[0][1:]

array([2, 3])

In [10]:
np.zeros (2)

array([0., 0.])

In [11]:
np.ones (3)

array([1., 1., 1.])

#### Sorting the array

In [12]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [13]:
np.sort (arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

#### Concat the array

In [14]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [15]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

#### Reshape the array

In [16]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [18]:
b = a.reshape(2, 3)
print(b)

[[0 1 2]
 [3 4 5]]


In [19]:
a

array([0, 1, 2, 3, 4, 5])

In [20]:
a[1:5]

array([1, 2, 3, 4])